export const ADD_ALL_DEPARTMENTS = 'ADD_ALL_DEPARTMENTS';

export const ADD_ALL_VACATIONS = 'ADD_ALL_VACATIONS';

export const ADD_ALL_USERS = 'ADD_ALL_USERS';

export const DELETE_THIS_VACATION = 'DELETE_THIS_VACATION';
// export const REQUEST_DELETE_THIS_VACATION = 'REQUEST_DELETE_THIS_VACATION';
export const WAITING_DELETE_VACATION = 'WAITING_DELETE_VACATION';
export const ERROR_DELETE_VACATION = 'ERROR_DELETE_VACATION';
export const SUCCESS_DELETE_VACATION = 'SUCCESS_DELETE_VACATION';

export const SET_VACATIONS = 'SET_VACATIONS';
export const WAITING_SET_VACATION = 'WAITING_SET_VACATION';
export const ERROR_SET_VACATION = 'ERROR_SET_VACATION';
export const SUCCESS_SET_VACATION = 'SUCCESS_SET_VACATION';

export const ADD_ALL_YEARS = 'ADD_ALL_YEARS';

export const ADD_THIS_USER = 'ADD_THIS_USER';